# Generated by Django 4.2.5 on 2023-10-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('accountID', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.PositiveIntegerField()),
                ('birthdate', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyAccountModel',
            fields=[
                ('userID', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderID', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('saleID', models.CharField(max_length=256)),
                ('total', models.DecimalField(decimal_places=2, max_digits=60)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'OrderDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('saleID', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('accountID', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('product_or_service', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sale',
                'managed': False,
            },
        ),
    ]
